FROM node:16.14-bullseye as build
WORKDIR /usr/src/network
RUN npm i -g npm@8.1
RUN npm config set \
	unsafe-perm=true \
	python="$(which python3)"
COPY . .
RUN npm run bootstrap-pkg -- streamr-network-tracker && npm run prune-pkg -- streamr-network-tracker

FROM node:16.14-bullseye-slim
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV:-production}
RUN apt-get update && apt-get --assume-yes --no-install-recommends install \
	curl=7.74.0-1.3+deb11u1 \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
RUN usermod -d /home/streamr -l streamr node && groupmod -n streamr node
USER streamr
WORKDIR /home/streamr/network
COPY --chown=streamr:streamr --from=build /usr/src/network/ .

ENV LOG_LEVEL=info

WORKDIR /home/streamr/network/packages/network-tracker

# start tracker
CMD ["./bin/tracker.js"]
