// @generated by protobuf-ts 2.8.2 with parameter server_generic,generate_dependencies,long_type_number
// @generated from protobuf file "packages/dht/protos/DhtRpc.proto" (package "dht", syntax proto3)
// tslint:disable
import { Empty } from "../../../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType as MessageType$ } from "@protobuf-ts/runtime";
import { RpcMessage } from "../../proto-rpc/protos/ProtoRpc";
import { Timestamp } from "../../../google/protobuf/timestamp";
import { Any } from "../../../google/protobuf/any";
// Used inside RpcMessage

/**
 * @generated from protobuf message dht.StoreDataRequest
 */
export interface StoreDataRequest {
    /**
     * @generated from protobuf field: bytes kademliaId = 1;
     */
    kademliaId: Uint8Array;
    /**
     * @generated from protobuf field: google.protobuf.Any data = 2;
     */
    data?: Any;
    /**
     * @generated from protobuf field: uint32 ttl = 3;
     */
    ttl: number;
}
/**
 * @generated from protobuf message dht.StoreDataResponse
 */
export interface StoreDataResponse {
    /**
     * @generated from protobuf field: string error = 1;
     */
    error: string;
}
/**
 * @generated from protobuf message dht.DataEntry
 */
export interface DataEntry {
    /**
     * @generated from protobuf field: dht.PeerDescriptor storer = 1;
     */
    storer?: PeerDescriptor;
    /**
     * @generated from protobuf field: google.protobuf.Any data = 2;
     */
    data?: Any;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp storedAt = 3;
     */
    storedAt?: Timestamp;
    /**
     * @generated from protobuf field: uint32 ttl = 4;
     */
    ttl: number; // milliseconds
}
// 
// message FindDataResult {
// bytes dataKey = 1;
// repeated DataEntry entries = 2;
// optional bool noCloserNodesFound = 3;
// }

/**
 * @generated from protobuf message dht.ClosestPeersRequest
 */
export interface ClosestPeersRequest {
    /**
     * @generated from protobuf field: bytes kademliaId = 1;
     */
    kademliaId: Uint8Array;
    /**
     * @generated from protobuf field: string requestId = 2;
     */
    requestId: string;
}
/**
 * @generated from protobuf message dht.ClosestPeersResponse
 */
export interface ClosestPeersResponse {
    /**
     * @generated from protobuf field: repeated dht.PeerDescriptor peers = 1;
     */
    peers: PeerDescriptor[];
    /**
     * @generated from protobuf field: string requestId = 2;
     */
    requestId: string;
}
/**
 * @generated from protobuf message dht.RecursiveFindRequest
 */
export interface RecursiveFindRequest {
    /**
     * @generated from protobuf field: string recursiveFindSessionId = 1;
     */
    recursiveFindSessionId: string;
    /**
     * @generated from protobuf field: dht.FindMode findMode = 2;
     */
    findMode: FindMode;
}
/**
 * @generated from protobuf message dht.RecursiveFindReport
 */
export interface RecursiveFindReport {
    /**
     * @generated from protobuf field: repeated dht.PeerDescriptor nodes = 1;
     */
    nodes: PeerDescriptor[];
    /**
     * optional bytes data = 2;
     *
     * @generated from protobuf field: repeated dht.DataEntry dataEntries = 2;
     */
    dataEntries: DataEntry[];
    /**
     * @generated from protobuf field: optional bool noCloserNodesFound = 3;
     */
    noCloserNodesFound?: boolean;
}
/**
 * @generated from protobuf message dht.PingRequest
 */
export interface PingRequest {
    /**
     * @generated from protobuf field: string requestId = 1;
     */
    requestId: string;
}
/**
 * @generated from protobuf message dht.PingResponse
 */
export interface PingResponse {
    /**
     * @generated from protobuf field: string requestId = 1;
     */
    requestId: string;
}
/**
 * @generated from protobuf message dht.LeaveNotice
 */
export interface LeaveNotice {
    /**
     * @generated from protobuf field: string serviceId = 1;
     */
    serviceId: string;
}
/**
 * @generated from protobuf message dht.PeerDescriptor
 */
export interface PeerDescriptor {
    /**
     * @generated from protobuf field: bytes kademliaId = 1;
     */
    kademliaId: Uint8Array;
    /**
     * @generated from protobuf field: dht.NodeType type = 2;
     */
    type: NodeType;
    /**
     * @generated from protobuf field: dht.ConnectivityMethod udp = 3;
     */
    udp?: ConnectivityMethod;
    /**
     * @generated from protobuf field: dht.ConnectivityMethod tcp = 4;
     */
    tcp?: ConnectivityMethod;
    /**
     * @generated from protobuf field: dht.ConnectivityMethod websocket = 5;
     */
    websocket?: ConnectivityMethod;
    /**
     * @generated from protobuf field: optional bool openInternet = 6;
     */
    openInternet?: boolean;
    /**
     * @generated from protobuf field: optional uint32 region = 7;
     */
    region?: number;
    /**
     * @generated from protobuf field: optional string nodeName = 8;
     */
    nodeName?: string;
}
/**
 * @generated from protobuf message dht.ConnectivityMethod
 */
export interface ConnectivityMethod {
    /**
     * @generated from protobuf field: uint32 port = 2;
     */
    port: number;
    /**
     * @generated from protobuf field: string ip = 3;
     */
    ip: string;
}
/**
 * @generated from protobuf message dht.ConnectivityReportRequest
 */
export interface ConnectivityReportRequest {
    /**
     * @generated from protobuf field: uint32 port = 1;
     */
    port: number;
    /**
     * @generated from protobuf field: string requestId = 2;
     */
    requestId: string;
}
/**
 * @generated from protobuf message dht.ConnectivityReportResponse
 */
export interface ConnectivityReportResponse {
    /**
     * @generated from protobuf field: string open_internet = 1;
     */
    openInternet: string;
    /**
     * @generated from protobuf field: string ip = 2;
     */
    ip: string;
    /**
     * @generated from protobuf field: string natType = 3;
     */
    natType: string;
    /**
     * @generated from protobuf field: string requestId = 4;
     */
    requestId: string;
}
/**
 * @generated from protobuf message dht.RouteMessageWrapper
 */
export interface RouteMessageWrapper {
    /**
     * @generated from protobuf field: dht.PeerDescriptor sourcePeer = 1;
     */
    sourcePeer?: PeerDescriptor;
    /**
     * @generated from protobuf field: string requestId = 2;
     */
    requestId: string;
    /**
     * @generated from protobuf field: dht.PeerDescriptor destinationPeer = 3;
     */
    destinationPeer?: PeerDescriptor;
    /**
     * @generated from protobuf field: dht.PeerDescriptor previousPeer = 4;
     */
    previousPeer?: PeerDescriptor;
    /**
     * @generated from protobuf field: dht.Message message = 5;
     */
    message?: Message;
    /**
     * @generated from protobuf field: repeated dht.PeerDescriptor reachableThrough = 6;
     */
    reachableThrough: PeerDescriptor[];
    /**
     * @generated from protobuf field: repeated dht.PeerDescriptor routingPath = 7;
     */
    routingPath: PeerDescriptor[];
}
/**
 * @generated from protobuf message dht.RouteMessageAck
 */
export interface RouteMessageAck {
    /**
     * @generated from protobuf field: dht.PeerDescriptor sourcePeer = 1;
     */
    sourcePeer?: PeerDescriptor;
    /**
     * @generated from protobuf field: string requestId = 2;
     */
    requestId: string;
    /**
     * @generated from protobuf field: dht.PeerDescriptor destinationPeer = 3;
     */
    destinationPeer?: PeerDescriptor;
    /**
     * @generated from protobuf field: string error = 4;
     */
    error: string;
}
// Correspond to the MessageType Enum

/**
 * @generated from protobuf message dht.ConnectivityRequest
 */
export interface ConnectivityRequest {
    /**
     * @generated from protobuf field: uint32 port = 1;
     */
    port: number;
}
/**
 * @generated from protobuf message dht.ConnectivityResponse
 */
export interface ConnectivityResponse {
    /**
     * @generated from protobuf field: bool open_internet = 1;
     */
    openInternet: boolean;
    /**
     * @generated from protobuf field: string ip = 2;
     */
    ip: string;
    /**
     * @generated from protobuf field: string natType = 3;
     */
    natType: string;
    /**
     * @generated from protobuf field: dht.ConnectivityMethod websocket = 4;
     */
    websocket?: ConnectivityMethod;
}
/**
 * @generated from protobuf message dht.HandshakeRequest
 */
export interface HandshakeRequest {
    /**
     * @generated from protobuf field: bytes sourceId = 1;
     */
    sourceId: Uint8Array;
    /**
     * @generated from protobuf field: string protocolVersion = 2;
     */
    protocolVersion: string;
    /**
     * @generated from protobuf field: dht.PeerDescriptor peerDescriptor = 3;
     */
    peerDescriptor?: PeerDescriptor;
}
/**
 * @generated from protobuf message dht.HandshakeResponse
 */
export interface HandshakeResponse {
    /**
     * @generated from protobuf field: bytes sourceId = 1;
     */
    sourceId: Uint8Array;
    /**
     * @generated from protobuf field: string protocolVersion = 2;
     */
    protocolVersion: string;
    /**
     * @generated from protobuf field: dht.PeerDescriptor peerDescriptor = 3;
     */
    peerDescriptor?: PeerDescriptor;
    /**
     * @generated from protobuf field: optional string responseError = 4;
     */
    responseError?: string;
}
/**
 * @generated from protobuf message dht.Message
 */
export interface Message {
    /**
     * @generated from protobuf field: string messageId = 1;
     */
    messageId: string;
    /**
     * @generated from protobuf field: dht.MessageType messageType = 2;
     */
    messageType: MessageType;
    /**
     * @generated from protobuf field: dht.PeerDescriptor sourceDescriptor = 3;
     */
    sourceDescriptor?: PeerDescriptor;
    /**
     * @generated from protobuf field: dht.PeerDescriptor targetDescriptor = 4;
     */
    targetDescriptor?: PeerDescriptor;
    /**
     * @generated from protobuf field: string serviceId = 5;
     */
    serviceId: string; // id of the RPC service
    /**
     * @generated from protobuf oneof: body
     */
    body: {
        oneofKind: "connectivityRequest";
        /**
         * @generated from protobuf field: dht.ConnectivityRequest connectivityRequest = 6;
         */
        connectivityRequest: ConnectivityRequest;
    } | {
        oneofKind: "connectivityResponse";
        /**
         * @generated from protobuf field: dht.ConnectivityResponse connectivityResponse = 7;
         */
        connectivityResponse: ConnectivityResponse;
    } | {
        oneofKind: "handshakeRequest";
        /**
         * @generated from protobuf field: dht.HandshakeRequest handshakeRequest = 8;
         */
        handshakeRequest: HandshakeRequest;
    } | {
        oneofKind: "handshakeResponse";
        /**
         * @generated from protobuf field: dht.HandshakeResponse handshakeResponse = 9;
         */
        handshakeResponse: HandshakeResponse;
    } | {
        oneofKind: "rpcMessage";
        /**
         * @generated from protobuf field: protorpc.RpcMessage rpcMessage = 10;
         */
        rpcMessage: RpcMessage;
    } | {
        oneofKind: "recursiveFindRequest";
        /**
         * @generated from protobuf field: dht.RecursiveFindRequest RecursiveFindRequest = 11 [json_name = "RecursiveFindRequest"];
         */
        recursiveFindRequest: RecursiveFindRequest;
    } | {
        oneofKind: undefined;
    };
}
// Connector Messages

/**
 * WebSocket
 *
 * @generated from protobuf message dht.WebSocketConnectionRequest
 */
export interface WebSocketConnectionRequest {
    /**
     * @generated from protobuf field: dht.PeerDescriptor requester = 1;
     */
    requester?: PeerDescriptor;
    /**
     * @generated from protobuf field: dht.PeerDescriptor target = 2;
     */
    target?: PeerDescriptor;
    /**
     * @generated from protobuf field: string ip = 3;
     */
    ip: string;
    /**
     * @generated from protobuf field: uint32 port = 4;
     */
    port: number;
}
/**
 * @generated from protobuf message dht.WebSocketConnectionResponse
 */
export interface WebSocketConnectionResponse {
    /**
     * @generated from protobuf field: dht.PeerDescriptor requester = 1;
     */
    requester?: PeerDescriptor;
    /**
     * @generated from protobuf field: dht.PeerDescriptor target = 2;
     */
    target?: PeerDescriptor;
    /**
     * @generated from protobuf field: bool accepted = 3;
     */
    accepted: boolean;
    /**
     * @generated from protobuf field: optional string reason = 4;
     */
    reason?: string;
}
/**
 * WebRTC
 *
 * @generated from protobuf message dht.WebRtcConnectionRequest
 */
export interface WebRtcConnectionRequest {
    /**
     * @generated from protobuf field: dht.PeerDescriptor requester = 1;
     */
    requester?: PeerDescriptor;
    /**
     * @generated from protobuf field: dht.PeerDescriptor target = 2;
     */
    target?: PeerDescriptor;
    /**
     * @generated from protobuf field: string connectionId = 3;
     */
    connectionId: string;
}
/**
 * @generated from protobuf message dht.RtcOffer
 */
export interface RtcOffer {
    /**
     * @generated from protobuf field: dht.PeerDescriptor requester = 1;
     */
    requester?: PeerDescriptor;
    /**
     * @generated from protobuf field: dht.PeerDescriptor target = 2;
     */
    target?: PeerDescriptor;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * @generated from protobuf field: string connectionId = 4;
     */
    connectionId: string;
}
/**
 * @generated from protobuf message dht.RtcAnswer
 */
export interface RtcAnswer {
    /**
     * @generated from protobuf field: dht.PeerDescriptor requester = 1;
     */
    requester?: PeerDescriptor;
    /**
     * @generated from protobuf field: dht.PeerDescriptor target = 2;
     */
    target?: PeerDescriptor;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * @generated from protobuf field: string connectionId = 4;
     */
    connectionId: string;
}
/**
 * @generated from protobuf message dht.IceCandidate
 */
export interface IceCandidate {
    /**
     * @generated from protobuf field: string candidate = 1;
     */
    candidate: string;
    /**
     * @generated from protobuf field: string mid = 2;
     */
    mid: string;
    /**
     * @generated from protobuf field: string connectionId = 3;
     */
    connectionId: string;
    /**
     * @generated from protobuf field: dht.PeerDescriptor requester = 4;
     */
    requester?: PeerDescriptor;
    /**
     * @generated from protobuf field: dht.PeerDescriptor target = 5;
     */
    target?: PeerDescriptor;
}
/**
 * @generated from protobuf message dht.LockRequest
 */
export interface LockRequest {
    /**
     * @generated from protobuf field: string protocolVersion = 1;
     */
    protocolVersion: string;
    /**
     * @generated from protobuf field: dht.PeerDescriptor peerDescriptor = 2;
     */
    peerDescriptor?: PeerDescriptor;
    /**
     * @generated from protobuf field: string serviceId = 3;
     */
    serviceId: string;
}
/**
 * @generated from protobuf message dht.UnlockRequest
 */
export interface UnlockRequest {
    /**
     * @generated from protobuf field: string protocolVersion = 1;
     */
    protocolVersion: string;
    /**
     * @generated from protobuf field: dht.PeerDescriptor peerDescriptor = 2;
     */
    peerDescriptor?: PeerDescriptor;
    /**
     * @generated from protobuf field: string serviceId = 3;
     */
    serviceId: string;
}
/**
 * @generated from protobuf message dht.LockResponse
 */
export interface LockResponse {
    /**
     * @generated from protobuf field: bool accepted = 1;
     */
    accepted: boolean;
    /**
     * @generated from protobuf field: optional bool reason = 2;
     */
    reason?: boolean; // if accepted = false
}
/**
 * @generated from protobuf message dht.DisconnectNotice
 */
export interface DisconnectNotice {
    /**
     * @generated from protobuf field: string protocolVersion = 1;
     */
    protocolVersion: string;
    /**
     * @generated from protobuf field: dht.PeerDescriptor peerDescriptor = 2;
     */
    peerDescriptor?: PeerDescriptor;
}
/**
 * @generated from protobuf enum dht.FindMode
 */
export enum FindMode {
    /**
     * @generated from protobuf enum value: NODE = 0;
     */
    NODE = 0,
    /**
     * @generated from protobuf enum value: DATA = 1;
     */
    DATA = 1
}
/**
 * @generated from protobuf enum dht.NodeType
 */
export enum NodeType {
    /**
     * @generated from protobuf enum value: NODEJS = 0;
     */
    NODEJS = 0,
    /**
     * @generated from protobuf enum value: BROWSER = 1;
     */
    BROWSER = 1,
    /**
     * @generated from protobuf enum value: VIRTUAL = 3;
     */
    VIRTUAL = 3
}
/**
 * @generated from protobuf enum dht.RpcResponseError
 */
export enum RpcResponseError {
    /**
     * @generated from protobuf enum value: SERVER_TIMOUT = 0;
     */
    SERVER_TIMOUT = 0,
    /**
     * @generated from protobuf enum value: CLIENT_TIMEOUT = 1;
     */
    CLIENT_TIMEOUT = 1,
    /**
     * @generated from protobuf enum value: SERVER_ERROR = 2;
     */
    SERVER_ERROR = 2,
    /**
     * @generated from protobuf enum value: UNKNOWN_RPC_METHOD = 3;
     */
    UNKNOWN_RPC_METHOD = 3
}
// protorpc.RpcMessage used as RpcMessage message type

// 
// message RpcMessage {
// map<string, string> header = 1;
// bytes body = 2;
// string requestId = 3;
// optional RpcResponseError responseError = 4;
// }

// Wraps all messages

/**
 * @generated from protobuf enum dht.MessageType
 */
export enum MessageType {
    /**
     * @generated from protobuf enum value: CONNECTIVITY_REQUEST = 0;
     */
    CONNECTIVITY_REQUEST = 0,
    /**
     * @generated from protobuf enum value: CONNECTIVITY_RESPONSE = 1;
     */
    CONNECTIVITY_RESPONSE = 1,
    /**
     * @generated from protobuf enum value: HANDSHAKE_REQUEST = 2;
     */
    HANDSHAKE_REQUEST = 2,
    /**
     * @generated from protobuf enum value: HANDSHAKE_RESPONSE = 3;
     */
    HANDSHAKE_RESPONSE = 3,
    /**
     * @generated from protobuf enum value: RPC = 4;
     */
    RPC = 4,
    /**
     * @generated from protobuf enum value: RECURSIVE_FIND_REQUEST = 5;
     */
    RECURSIVE_FIND_REQUEST = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class StoreDataRequest$Type extends MessageType$<StoreDataRequest> {
    constructor() {
        super("dht.StoreDataRequest", [
            { no: 1, name: "kademliaId", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "data", kind: "message", T: () => Any },
            { no: 3, name: "ttl", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.StoreDataRequest
 */
export const StoreDataRequest = new StoreDataRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StoreDataResponse$Type extends MessageType$<StoreDataResponse> {
    constructor() {
        super("dht.StoreDataResponse", [
            { no: 1, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.StoreDataResponse
 */
export const StoreDataResponse = new StoreDataResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DataEntry$Type extends MessageType$<DataEntry> {
    constructor() {
        super("dht.DataEntry", [
            { no: 1, name: "storer", kind: "message", T: () => PeerDescriptor },
            { no: 2, name: "data", kind: "message", T: () => Any },
            { no: 3, name: "storedAt", kind: "message", T: () => Timestamp },
            { no: 4, name: "ttl", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.DataEntry
 */
export const DataEntry = new DataEntry$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClosestPeersRequest$Type extends MessageType$<ClosestPeersRequest> {
    constructor() {
        super("dht.ClosestPeersRequest", [
            { no: 1, name: "kademliaId", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "requestId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.ClosestPeersRequest
 */
export const ClosestPeersRequest = new ClosestPeersRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClosestPeersResponse$Type extends MessageType$<ClosestPeersResponse> {
    constructor() {
        super("dht.ClosestPeersResponse", [
            { no: 1, name: "peers", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PeerDescriptor },
            { no: 2, name: "requestId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.ClosestPeersResponse
 */
export const ClosestPeersResponse = new ClosestPeersResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecursiveFindRequest$Type extends MessageType$<RecursiveFindRequest> {
    constructor() {
        super("dht.RecursiveFindRequest", [
            { no: 1, name: "recursiveFindSessionId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "findMode", kind: "enum", T: () => ["dht.FindMode", FindMode] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.RecursiveFindRequest
 */
export const RecursiveFindRequest = new RecursiveFindRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecursiveFindReport$Type extends MessageType$<RecursiveFindReport> {
    constructor() {
        super("dht.RecursiveFindReport", [
            { no: 1, name: "nodes", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PeerDescriptor },
            { no: 2, name: "dataEntries", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => DataEntry },
            { no: 3, name: "noCloserNodesFound", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.RecursiveFindReport
 */
export const RecursiveFindReport = new RecursiveFindReport$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PingRequest$Type extends MessageType$<PingRequest> {
    constructor() {
        super("dht.PingRequest", [
            { no: 1, name: "requestId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.PingRequest
 */
export const PingRequest = new PingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PingResponse$Type extends MessageType$<PingResponse> {
    constructor() {
        super("dht.PingResponse", [
            { no: 1, name: "requestId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.PingResponse
 */
export const PingResponse = new PingResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LeaveNotice$Type extends MessageType$<LeaveNotice> {
    constructor() {
        super("dht.LeaveNotice", [
            { no: 1, name: "serviceId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.LeaveNotice
 */
export const LeaveNotice = new LeaveNotice$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PeerDescriptor$Type extends MessageType$<PeerDescriptor> {
    constructor() {
        super("dht.PeerDescriptor", [
            { no: 1, name: "kademliaId", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["dht.NodeType", NodeType] },
            { no: 3, name: "udp", kind: "message", T: () => ConnectivityMethod },
            { no: 4, name: "tcp", kind: "message", T: () => ConnectivityMethod },
            { no: 5, name: "websocket", kind: "message", T: () => ConnectivityMethod },
            { no: 6, name: "openInternet", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "region", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 8, name: "nodeName", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.PeerDescriptor
 */
export const PeerDescriptor = new PeerDescriptor$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectivityMethod$Type extends MessageType$<ConnectivityMethod> {
    constructor() {
        super("dht.ConnectivityMethod", [
            { no: 2, name: "port", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "ip", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.ConnectivityMethod
 */
export const ConnectivityMethod = new ConnectivityMethod$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectivityReportRequest$Type extends MessageType$<ConnectivityReportRequest> {
    constructor() {
        super("dht.ConnectivityReportRequest", [
            { no: 1, name: "port", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "requestId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.ConnectivityReportRequest
 */
export const ConnectivityReportRequest = new ConnectivityReportRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectivityReportResponse$Type extends MessageType$<ConnectivityReportResponse> {
    constructor() {
        super("dht.ConnectivityReportResponse", [
            { no: 1, name: "open_internet", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ip", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "natType", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "requestId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.ConnectivityReportResponse
 */
export const ConnectivityReportResponse = new ConnectivityReportResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RouteMessageWrapper$Type extends MessageType$<RouteMessageWrapper> {
    constructor() {
        super("dht.RouteMessageWrapper", [
            { no: 1, name: "sourcePeer", kind: "message", T: () => PeerDescriptor },
            { no: 2, name: "requestId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "destinationPeer", kind: "message", T: () => PeerDescriptor },
            { no: 4, name: "previousPeer", kind: "message", T: () => PeerDescriptor },
            { no: 5, name: "message", kind: "message", T: () => Message },
            { no: 6, name: "reachableThrough", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PeerDescriptor },
            { no: 7, name: "routingPath", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PeerDescriptor }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.RouteMessageWrapper
 */
export const RouteMessageWrapper = new RouteMessageWrapper$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RouteMessageAck$Type extends MessageType$<RouteMessageAck> {
    constructor() {
        super("dht.RouteMessageAck", [
            { no: 1, name: "sourcePeer", kind: "message", T: () => PeerDescriptor },
            { no: 2, name: "requestId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "destinationPeer", kind: "message", T: () => PeerDescriptor },
            { no: 4, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.RouteMessageAck
 */
export const RouteMessageAck = new RouteMessageAck$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectivityRequest$Type extends MessageType$<ConnectivityRequest> {
    constructor() {
        super("dht.ConnectivityRequest", [
            { no: 1, name: "port", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.ConnectivityRequest
 */
export const ConnectivityRequest = new ConnectivityRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectivityResponse$Type extends MessageType$<ConnectivityResponse> {
    constructor() {
        super("dht.ConnectivityResponse", [
            { no: 1, name: "open_internet", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "ip", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "natType", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "websocket", kind: "message", T: () => ConnectivityMethod }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.ConnectivityResponse
 */
export const ConnectivityResponse = new ConnectivityResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HandshakeRequest$Type extends MessageType$<HandshakeRequest> {
    constructor() {
        super("dht.HandshakeRequest", [
            { no: 1, name: "sourceId", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "protocolVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "peerDescriptor", kind: "message", T: () => PeerDescriptor }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.HandshakeRequest
 */
export const HandshakeRequest = new HandshakeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HandshakeResponse$Type extends MessageType$<HandshakeResponse> {
    constructor() {
        super("dht.HandshakeResponse", [
            { no: 1, name: "sourceId", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "protocolVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "peerDescriptor", kind: "message", T: () => PeerDescriptor },
            { no: 4, name: "responseError", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.HandshakeResponse
 */
export const HandshakeResponse = new HandshakeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Message$Type extends MessageType$<Message> {
    constructor() {
        super("dht.Message", [
            { no: 1, name: "messageId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "messageType", kind: "enum", T: () => ["dht.MessageType", MessageType] },
            { no: 3, name: "sourceDescriptor", kind: "message", T: () => PeerDescriptor },
            { no: 4, name: "targetDescriptor", kind: "message", T: () => PeerDescriptor },
            { no: 5, name: "serviceId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "connectivityRequest", kind: "message", oneof: "body", T: () => ConnectivityRequest },
            { no: 7, name: "connectivityResponse", kind: "message", oneof: "body", T: () => ConnectivityResponse },
            { no: 8, name: "handshakeRequest", kind: "message", oneof: "body", T: () => HandshakeRequest },
            { no: 9, name: "handshakeResponse", kind: "message", oneof: "body", T: () => HandshakeResponse },
            { no: 10, name: "rpcMessage", kind: "message", oneof: "body", T: () => RpcMessage },
            { no: 11, name: "RecursiveFindRequest", kind: "message", jsonName: "RecursiveFindRequest", oneof: "body", T: () => RecursiveFindRequest }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.Message
 */
export const Message = new Message$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WebSocketConnectionRequest$Type extends MessageType$<WebSocketConnectionRequest> {
    constructor() {
        super("dht.WebSocketConnectionRequest", [
            { no: 1, name: "requester", kind: "message", T: () => PeerDescriptor },
            { no: 2, name: "target", kind: "message", T: () => PeerDescriptor },
            { no: 3, name: "ip", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "port", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.WebSocketConnectionRequest
 */
export const WebSocketConnectionRequest = new WebSocketConnectionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WebSocketConnectionResponse$Type extends MessageType$<WebSocketConnectionResponse> {
    constructor() {
        super("dht.WebSocketConnectionResponse", [
            { no: 1, name: "requester", kind: "message", T: () => PeerDescriptor },
            { no: 2, name: "target", kind: "message", T: () => PeerDescriptor },
            { no: 3, name: "accepted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "reason", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.WebSocketConnectionResponse
 */
export const WebSocketConnectionResponse = new WebSocketConnectionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WebRtcConnectionRequest$Type extends MessageType$<WebRtcConnectionRequest> {
    constructor() {
        super("dht.WebRtcConnectionRequest", [
            { no: 1, name: "requester", kind: "message", T: () => PeerDescriptor },
            { no: 2, name: "target", kind: "message", T: () => PeerDescriptor },
            { no: 3, name: "connectionId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.WebRtcConnectionRequest
 */
export const WebRtcConnectionRequest = new WebRtcConnectionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RtcOffer$Type extends MessageType$<RtcOffer> {
    constructor() {
        super("dht.RtcOffer", [
            { no: 1, name: "requester", kind: "message", T: () => PeerDescriptor },
            { no: 2, name: "target", kind: "message", T: () => PeerDescriptor },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "connectionId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.RtcOffer
 */
export const RtcOffer = new RtcOffer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RtcAnswer$Type extends MessageType$<RtcAnswer> {
    constructor() {
        super("dht.RtcAnswer", [
            { no: 1, name: "requester", kind: "message", T: () => PeerDescriptor },
            { no: 2, name: "target", kind: "message", T: () => PeerDescriptor },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "connectionId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.RtcAnswer
 */
export const RtcAnswer = new RtcAnswer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IceCandidate$Type extends MessageType$<IceCandidate> {
    constructor() {
        super("dht.IceCandidate", [
            { no: 1, name: "candidate", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "mid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "connectionId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "requester", kind: "message", T: () => PeerDescriptor },
            { no: 5, name: "target", kind: "message", T: () => PeerDescriptor }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.IceCandidate
 */
export const IceCandidate = new IceCandidate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LockRequest$Type extends MessageType$<LockRequest> {
    constructor() {
        super("dht.LockRequest", [
            { no: 1, name: "protocolVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "peerDescriptor", kind: "message", T: () => PeerDescriptor },
            { no: 3, name: "serviceId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.LockRequest
 */
export const LockRequest = new LockRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UnlockRequest$Type extends MessageType$<UnlockRequest> {
    constructor() {
        super("dht.UnlockRequest", [
            { no: 1, name: "protocolVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "peerDescriptor", kind: "message", T: () => PeerDescriptor },
            { no: 3, name: "serviceId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.UnlockRequest
 */
export const UnlockRequest = new UnlockRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LockResponse$Type extends MessageType$<LockResponse> {
    constructor() {
        super("dht.LockResponse", [
            { no: 1, name: "accepted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "reason", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.LockResponse
 */
export const LockResponse = new LockResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DisconnectNotice$Type extends MessageType$<DisconnectNotice> {
    constructor() {
        super("dht.DisconnectNotice", [
            { no: 1, name: "protocolVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "peerDescriptor", kind: "message", T: () => PeerDescriptor }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message dht.DisconnectNotice
 */
export const DisconnectNotice = new DisconnectNotice$Type();
/**
 * @generated ServiceType for protobuf service dht.DhtRpcService
 */
export const DhtRpcService = new ServiceType("dht.DhtRpcService", [
    { name: "getClosestPeers", options: {}, I: ClosestPeersRequest, O: ClosestPeersResponse },
    { name: "ping", options: {}, I: PingRequest, O: PingResponse },
    { name: "routeMessage", options: {}, I: RouteMessageWrapper, O: RouteMessageAck },
    { name: "findRecursively", options: {}, I: RouteMessageWrapper, O: RouteMessageAck },
    { name: "forwardMessage", options: {}, I: RouteMessageWrapper, O: RouteMessageAck },
    { name: "leaveNotice", options: {}, I: LeaveNotice, O: Empty },
    { name: "storeData", options: {}, I: StoreDataRequest, O: StoreDataResponse }
]);
/**
 * @generated ServiceType for protobuf service dht.RecursiveFindSessionService
 */
export const RecursiveFindSessionService = new ServiceType("dht.RecursiveFindSessionService", [
    { name: "reportRecursiveFindResult", options: {}, I: RecursiveFindReport, O: Empty }
]);
/**
 * @generated ServiceType for protobuf service dht.WebSocketConnectorService
 */
export const WebSocketConnectorService = new ServiceType("dht.WebSocketConnectorService", [
    { name: "requestConnection", options: {}, I: WebSocketConnectionRequest, O: WebSocketConnectionResponse }
]);
/**
 * @generated ServiceType for protobuf service dht.WebRtcConnectorService
 */
export const WebRtcConnectorService = new ServiceType("dht.WebRtcConnectorService", [
    { name: "requestConnection", options: {}, I: WebRtcConnectionRequest, O: Empty },
    { name: "rtcOffer", options: {}, I: RtcOffer, O: Empty },
    { name: "rtcAnswer", options: {}, I: RtcAnswer, O: Empty },
    { name: "iceCandidate", options: {}, I: IceCandidate, O: Empty }
]);
/**
 * @generated ServiceType for protobuf service dht.ConnectionLocker
 */
export const ConnectionLocker = new ServiceType("dht.ConnectionLocker", [
    { name: "lockRequest", options: {}, I: LockRequest, O: LockResponse },
    { name: "unlockRequest", options: {}, I: UnlockRequest, O: Empty },
    { name: "gracefulDisconnect", options: {}, I: DisconnectNotice, O: Empty }
]);
