// @generated by protobuf-ts 2.8.0 with parameter server_generic,generate_dependencies
// @generated from protobuf file "packages/trackerless-network/protos/NetworkRpc.proto" (syntax proto3)
// tslint:disable
import { NeighborUpdate } from "./NetworkRpc";
import { InterleaveNotice } from "./NetworkRpc";
import { LeaveNotice } from "./NetworkRpc";
import { HandshakeResponse } from "./NetworkRpc";
import { HandshakeRequest } from "./NetworkRpc";
import { Empty } from "../../../google/protobuf/empty";
import { DataMessage } from "./NetworkRpc";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service NetworkRpc
 */
export interface INetworkRpc<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: sendData(DataMessage) returns (google.protobuf.Empty);
     */
    sendData(request: DataMessage, context: T): Promise<Empty>;
    /**
     * @generated from protobuf rpc: handshake(HandshakeRequest) returns (HandshakeResponse);
     */
    handshake(request: HandshakeRequest, context: T): Promise<HandshakeResponse>;
    /**
     * @generated from protobuf rpc: leaveNotice(LeaveNotice) returns (google.protobuf.Empty);
     */
    leaveNotice(request: LeaveNotice, context: T): Promise<Empty>;
    /**
     * @generated from protobuf rpc: interleaveNotice(InterleaveNotice) returns (google.protobuf.Empty);
     */
    interleaveNotice(request: InterleaveNotice, context: T): Promise<Empty>;
    /**
     * @generated from protobuf rpc: neighborUpdate(NeighborUpdate) returns (NeighborUpdate);
     */
    neighborUpdate(request: NeighborUpdate, context: T): Promise<NeighborUpdate>;
}
