// @generated by protobuf-ts 2.6.0 with parameter server_generic,generate_dependencies
// @generated from protobuf file "NotificationRpc.proto" (syntax proto3)
// tslint:disable
import { NotificationResponse } from "./ProtoRpc";
import { WakeUpRequest } from "./NotificationRpc";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service NotificationRpc
 */
export interface INotificationRpc<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: wakeUp(WakeUpRequest) returns (NotificationResponse);
     */
    wakeUp(request: WakeUpRequest, context: T): Promise<NotificationResponse>;
}
