// @generated by protobuf-ts 2.8.0 with parameter server_generic,generate_dependencies
// @generated from protobuf file "RoutedHelloRpc.proto" (syntax proto3)
// tslint:disable
import { RoutedHelloResponse } from './RoutedHelloRpc'
import { RoutedHelloRequest } from './RoutedHelloRpc'
import { ServerCallContext } from '@protobuf-ts/runtime-rpc'
/**
 * @generated from protobuf service RoutedHelloRpcService
 */
export interface IRoutedHelloRpcService<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: sayHello(RoutedHelloRequest) returns (RoutedHelloResponse);
     */
    sayHello(request: RoutedHelloRequest, context: T): Promise<RoutedHelloResponse>
}
