#!/bin/sh
BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

# don't run hook when rebasing/merging
if [ $BRANCH_NAME != "(no branch)" ] && [ ! -f .git/MERGE_MSG ]
then
    . "$(dirname "$0")/_/husky.sh"

    npx --no-install commitlint --edit
fi
